#!/usr/bin/env python3
"""
DeskMan Agent Builder
Compiles the endpoint agent into a standalone .exe using PyInstaller.
Embeds the Supabase credentials so the EXE runs without any CLI arguments.

Usage:
    python build.py --url <SUPABASE_URL> --key <SERVICE_ROLE_KEY>

Optional:
    --name <exe_name>        Output executable name (default: deskman_agent)
    --icon <path_to_icon>    Custom icon for the EXE
    --onefile                Single-file EXE (default, larger but portable)
    --heartbeat <seconds>    Heartbeat interval (default: 30)
    --poll <seconds>         Command poll interval (default: 2)
    --noconsole              Hide console window on target (runs silently)
"""

import argparse
import os
import shutil
import subprocess
import sys
import textwrap


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_TEMPLATE = os.path.join(SCRIPT_DIR, "embedded_config.py")
AGENT_SCRIPT = os.path.join(SCRIPT_DIR, "deskman_agent.py")
BUILD_DIR = os.path.join(SCRIPT_DIR, "build")
DIST_DIR = os.path.join(SCRIPT_DIR, "dist")


def write_embedded_config(url: str, key: str, heartbeat: int, poll: int):
    """Write the Supabase credentials into embedded_config.py."""
    config_content = textwrap.dedent(f"""\
        # DeskMan Agent - Embedded Configuration
        # Auto-generated by build.py — DO NOT edit manually.

        SUPABASE_URL = "{url}"
        SUPABASE_KEY = "{key}"
        HEARTBEAT_INTERVAL = {heartbeat}
        COMMAND_POLL_INTERVAL = {poll}
    """)
    with open(CONFIG_TEMPLATE, "w") as f:
        f.write(config_content)
    print(f"[+] Embedded config written with URL: {url}")


def restore_config_template():
    """Reset embedded_config.py back to placeholder values."""
    config_content = textwrap.dedent("""\
        # DeskMan Agent - Embedded Configuration
        # This file is auto-populated by the build script before compiling to EXE.
        # DO NOT edit manually — use build.py to generate a configured executable.

        SUPABASE_URL = "__SUPABASE_URL__"
        SUPABASE_KEY = "__SUPABASE_KEY__"
        HEARTBEAT_INTERVAL = 30
        COMMAND_POLL_INTERVAL = 2
    """)
    with open(CONFIG_TEMPLATE, "w") as f:
        f.write(config_content)


def check_pyinstaller():
    """Ensure PyInstaller is installed."""
    try:
        import PyInstaller
        print(f"[+] PyInstaller {PyInstaller.__version__} found")
        return True
    except ImportError:
        print("[-] PyInstaller not found. Installing...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller"])
        print("[+] PyInstaller installed")
        return True


def check_dependencies():
    """Ensure all agent dependencies are installed."""
    deps = ["supabase", "psutil", "mss", "PIL"]
    missing = []
    for dep in deps:
        try:
            __import__(dep)
        except ImportError:
            missing.append(dep)

    if missing:
        print(f"[!] Missing packages: {', '.join(missing)}")
        print("[*] Installing from requirements.txt...")
        req_file = os.path.join(SCRIPT_DIR, "requirements.txt")
        if os.path.exists(req_file):
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", req_file])
        else:
            # Install individually
            pip_names = {"PIL": "Pillow"}
            for dep in missing:
                pkg = pip_names.get(dep, dep)
                subprocess.check_call([sys.executable, "-m", "pip", "install", pkg])
        print("[+] Dependencies installed")


def build_exe(name: str, icon: str = None, onefile: bool = True, noconsole: bool = False):
    """Run PyInstaller to compile the agent."""

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--name", name,
        "--clean",
        "--noconfirm",
        "--distpath", DIST_DIR,
        "--workpath", BUILD_DIR,
    ]

    if onefile:
        cmd.append("--onefile")

    if noconsole:
        cmd.append("--noconsole")

    if icon and os.path.exists(icon):
        cmd.extend(["--icon", icon])

    # Add the embedded_config as a data file so it's bundled
    sep = ";" if sys.platform == "win32" else ":"
    cmd.extend(["--add-data", f"{CONFIG_TEMPLATE}{sep}."])

    # Hidden imports that PyInstaller may miss
    hidden = [
        "supabase",
        "gotrue",
        "postgrest",
        "storage3",
        "realtime",
        "supafunc",
        "psutil",
        "mss",
        "PIL",
        "PIL.Image",
    ]
    for h in hidden:
        cmd.extend(["--hidden-import", h])

    cmd.append(AGENT_SCRIPT)

    print(f"\n[*] Running PyInstaller...")
    print(f"    Command: {' '.join(cmd)}\n")

    result = subprocess.run(cmd)

    if result.returncode == 0:
        if onefile:
            ext = ".exe" if sys.platform == "win32" else ""
            exe_path = os.path.join(DIST_DIR, f"{name}{ext}")
            size_mb = os.path.getsize(exe_path) / (1024 * 1024) if os.path.exists(exe_path) else 0
            print(f"\n[+] Build successful!")
            print(f"[+] Output: {exe_path}")
            print(f"[+] Size: {size_mb:.1f} MB")
        else:
            print(f"\n[+] Build successful!")
            print(f"[+] Output directory: {os.path.join(DIST_DIR, name)}")
    else:
        print(f"\n[-] Build failed with exit code {result.returncode}")
        sys.exit(1)

    return result.returncode


def main():
    print("=" * 60)
    print("  DeskMan Agent Builder")
    print("=" * 60)
    print()

    parser = argparse.ArgumentParser(
        description="Build DeskMan agent into a standalone executable"
    )
    parser.add_argument(
        "--url", required=True,
        help="Supabase project URL"
    )
    parser.add_argument(
        "--key", required=True,
        help="Supabase service_role key"
    )
    parser.add_argument(
        "--name", default="deskman_agent",
        help="Output executable name (default: deskman_agent)"
    )
    parser.add_argument(
        "--icon", default=None,
        help="Path to .ico file for the executable"
    )
    parser.add_argument(
        "--onefile", action="store_true", default=True,
        help="Build as single-file EXE (default)"
    )
    parser.add_argument(
        "--onedir", action="store_true", default=False,
        help="Build as directory instead of single file"
    )
    parser.add_argument(
        "--noconsole", action="store_true", default=False,
        help="Hide console window (run silently in background)"
    )
    parser.add_argument(
        "--heartbeat", type=int, default=30,
        help="Heartbeat interval in seconds (default: 30)"
    )
    parser.add_argument(
        "--poll", type=int, default=2,
        help="Command poll interval in seconds (default: 2)"
    )

    args = parser.parse_args()
    onefile = not args.onedir

    try:
        # Step 1: Check dependencies
        print("[1/4] Checking dependencies...")
        check_pyinstaller()
        check_dependencies()

        # Step 2: Write embedded config
        print("\n[2/4] Embedding configuration...")
        write_embedded_config(args.url, args.key, args.heartbeat, args.poll)

        # Step 3: Build
        print(f"\n[3/4] Building {'single-file' if onefile else 'directory'} executable...")
        build_exe(
            name=args.name,
            icon=args.icon,
            onefile=onefile,
            noconsole=args.noconsole,
        )

        # Step 4: Cleanup — restore template so credentials aren't left in source
        print("\n[4/4] Cleaning up...")
        restore_config_template()
        # Remove build artifacts (keep dist/)
        if os.path.exists(BUILD_DIR):
            shutil.rmtree(BUILD_DIR, ignore_errors=True)
        spec_file = os.path.join(SCRIPT_DIR, f"{args.name}.spec")
        if os.path.exists(spec_file):
            os.remove(spec_file)

        print("\n" + "=" * 60)
        print("  Build Complete!")
        print(f"  Deploy the executable from: {DIST_DIR}/")
        print("  The EXE has your Supabase credentials embedded.")
        print("  Just run it on any target PC — no Python needed.")
        print("=" * 60)

    except KeyboardInterrupt:
        print("\n[!] Build cancelled")
        restore_config_template()
        sys.exit(1)
    except Exception as e:
        print(f"\n[-] Build error: {e}")
        restore_config_template()
        sys.exit(1)


if __name__ == "__main__":
    main()
